language: node_js
node_js: '14.15.0'

cache:
  yarn: true
  directories:
    - node_modules


install:
  - yarn --frozen-lockfile --non-interactive
  - yarn run build
before_deploy: "echo 'ready?'"
deploy:
  provider: heroku
  api_key:
    master: $HEROKU_TOKEN
    develop: $HEROKU_TOKEN
  app:
    main: congratulations-elocont
