query {
    eventType(code: "birthday") {
        name
        color
        slug
        events {
            id
            title
            description
            day
            month
            user {
               id
                name
                avatar
            }
        }
    }
}

